seed: 42
learning_rate: 2.0e-04
lr_scheduler_type: linear
# num_train_epochs: 2
total_train_examples: 23000 # num_train_epochs will be determined to make the total number of examples near this value
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
warmup_ratio: 0.03
weight_decay: 0
logging_strategy: steps
logging_steps: 100
eval_strategy: steps
eval_steps: 500
save_strategy: steps
save_steps: 500
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
gradient_accumulation_steps: 1
max_grad_norm: 1.0
bf16: true
fp16: false
report_to: tensorboard
